import { createRequire } from "node:module";
import { homedir, platform } from "node:os";
import { join } from "node:path";

/**
 * Hardcoded fallback for `CONNECTOR_UPSTREAM_URL` when nothing is configured.
 * Used as a last-resort default only; runtime user-facing strings always
 * interpolate whichever URL is actually chosen (`authUrl`, `toolpanelUrl`,
 * or the resolved base URL after the toolpanel liveness probe).
 */
export const DEFAULT_AUTH_URL =
  (process.env.CONNECTOR_DEFAULT_UPSTREAM_URL?.trim())
  || "https://toolrator.com";

/**
 * The product name driving every product-derived identifier: the config-dir
 * subfolder, the implicit default search-engine id (`${productName}-default`),
 * and any user-facing string that mentions the product. Override via
 * `CONNECTOR_PRODUCT_NAME`. Defaults to `"toolconnector"`.
 */
export const PRODUCT_NAME =
  (process.env.CONNECTOR_PRODUCT_NAME?.trim())
  || "toolconnector";

/**
 * The id of the implicit default search engine generated by `search-config.ts`
 * when no engines are configured. Derived from `PRODUCT_NAME`.
 */
export const DEFAULT_ENGINE_ID = `${PRODUCT_NAME}-default`;

/**
 * Default base URL of the local toolpanel instance when none is configured.
 * Toolpanel serves `/.well-known/toolpanel-alive` at this origin; the
 * connector probes it on every boot to decide whether to prefer toolpanel
 * over the configured upstream URL.
 */
export const DEFAULT_TOOLPANEL_URL = "http://127.0.0.1:7800";

/**
 * Path of the toolpanel liveness endpoint. Appended to `TOOLPANEL_URL` to
 * form the URL the connector probes (a `GET`; expected to return 204).
 * Configurable via `TOOLPANEL_PROBE_PATH`; defaults to `/.well-known/toolpanel-alive`.
 */
export const TOOLPANEL_PROBE_PATH =
  (process.env.TOOLPANEL_PROBE_PATH?.trim())
  || "/.well-known/toolpanel-alive";

/**
 * Timeout for the toolpanel liveness probe. Short by intent: if toolpanel
 * is offline, the probe should fail quickly and the connector should fall
 * back to the SaaS upstream. Configurable via `TOOLPANEL_PROBE_TIMEOUT_MS`
 * (positive integer ms); defaults to 1500.
 */
export const TOOLPANEL_PROBE_TIMEOUT_MS = (() => {
  const raw = process.env.TOOLPANEL_PROBE_TIMEOUT_MS?.trim();
  if (raw) {
    const n = Number.parseInt(raw, 10);
    if (Number.isFinite(n) && n > 0) return n;
  }
  return 1_500;
})();

export interface ToolconnectorConfig {
  /** Pre-configured API key (skips login flow) */
  apiKey: string;
  /** Directory for storing credentials */
  configDir: string;
  /**
   * Base URL of the account/control-plane backend the connector talks to
   * for auth. Defaults to `CONNECTOR_UPSTREAM_URL` (`DEFAULT_AUTH_URL` as
   * last-resort fallback). When a toolpanel instance is reachable, the
   * connector prefers `${toolpanelUrl}` as the source of truth.
   */
  authUrl: string;
  /**
   * Base URL of a self-hostable toolpanel instance, when one is available.
   * The connector probes `${toolpanelUrl}${TOOLPANEL_PROBE_PATH}` at boot;
   * if that returns 200/204, toolpanel is preferred over `authUrl`.
   * Empty string disables probing entirely.
   */
  toolpanelUrl: string;
  /** Logging verbosity */
  logLevel: "debug" | "info" | "warn" | "error";
  /**
   * Mode for search engines config updates.
   *   "auto"     — authenticated: toolpanel (if alive) → configured upstream → local file
   *   "file"     — local file (or CONNECTOR_SEARCH_CONFIG) only; never probe
   *   "toolpanel"— authenticated: toolpanel ONLY; verify-key/auto-pull must succeed against it
   */
  searchConfigMode: "auto" | "file" | "toolpanel";
  /** Overridden search engines configuration file path */
  searchConfigPath: string;
  /**
   * Whether the connector should auto-probe `${toolpanelUrl}${TOOLPANEL_PROBE_PATH}`
   * at boot. Defaults to `"auto"` (probe when `toolpanelUrl` is set and
   * `searchConfigMode !== "file"`). Hardline SaaS users can set the env
   * `TOOLPANEL_DISCOVERY=off` to skip the probe entirely.
   */
  toolpanelDiscovery: "auto" | "off";
}

function normalizeSearchConfigMode(raw: string): ToolconnectorConfig["searchConfigMode"] {
  const v = raw.trim().toLowerCase();
  if (v === "file") return "file";
  if (v === "toolpanel") return "toolpanel";
  return "auto";
}

function normalizeToolpanelDiscovery(raw: string): ToolconnectorConfig["toolpanelDiscovery"] {
  const v = raw.trim().toLowerCase();
  if (v === "off" || v === "0" || v === "false" || v === "no") return "off";
  return "auto";
}

type LogLevel = ToolconnectorConfig["logLevel"];

/**
 * Connector version. Sourced from the package manifest, overridable via the
 * TOOLCONNECTOR_VERSION env variable. Never hardcoded.
 */
function resolveConnectorVersion(): string {
  const envVersion = process.env.TOOLCONNECTOR_VERSION?.trim();
  if (envVersion) {
    return envVersion;
  }
  try {
    const pkg = createRequire(import.meta.url)("../package.json") as { version?: string };
    const manifestVersion = pkg.version?.trim();
    if (manifestVersion) {
      return manifestVersion;
    }
  } catch {
    /* manifest unavailable — fall back to an empty string */
  }
  return "";
}

export const TOOLCONNECTOR_VERSION = resolveConnectorVersion();

const LOG_LEVELS: Record<LogLevel, number> = {
  debug: 0,
  info: 1,
  warn: 2,
  error: 3,
};

/**
 * Returns the OS-appropriate default configuration directory for this product.
 *
 * - Windows: %APPDATA%\<productName>
 * - macOS:   ~/Library/Application Support/<productName>
 * - Linux:   $XDG_CONFIG_HOME/<productName> (fallback: ~/.config/<productName>)
 *
 * `<productName>` is `CONNECTOR_PRODUCT_NAME` (default `toolconnector`).
 */
function defaultConfigDir(): string {
  const os = platform();
  const product = PRODUCT_NAME;

  if (os === "win32") {
    const appData = process.env.APPDATA;
    if (appData) {
      return join(appData, product);
    }
    return join(homedir(), "AppData", "Roaming", product);
  }

  if (os === "darwin") {
    return join(homedir(), "Library", "Application Support", product);
  }

  // Linux and others: follow XDG Base Directory spec
  const xdgConfig = process.env.XDG_CONFIG_HOME;
  if (xdgConfig) {
    return join(xdgConfig, product);
  }
  return join(homedir(), ".config", product);
}

function readEnvString(keys: string[], fallback: string): string {
  for (const key of keys) {
    const value = process.env[key];
    if (typeof value === "string" && value.trim() !== "") {
      return value.trim();
    }
  }
  return fallback;
}

function normalizeLogLevel(input: string): LogLevel {
  const v = input.trim().toLowerCase();
  if (v === "debug" || v === "info" || v === "warn" || v === "error") {
    return v;
  }
  return "info";
}

export function loadConfig(): ToolconnectorConfig {
  const apiKey = readEnvString(["CONNECTOR_API_KEY"], "");

  const configDir = readEnvString(
    ["CONNECTOR_CONFIG_DIR"],
    defaultConfigDir(),
  );

  const authUrl = readEnvString(
    ["CONNECTOR_UPSTREAM_URL"],
    DEFAULT_AUTH_URL,
  ).replace(/\/+$/, "");

  const toolpanelUrl = readEnvString(
    ["TOOLPANEL_URL"],
    DEFAULT_TOOLPANEL_URL,
  ).replace(/\/+$/, "");

  const logLevel = normalizeLogLevel(
    readEnvString(["CONNECTOR_LOG_LEVEL"], "info"),
  );

  const searchConfigPath = readEnvString(
    ["CONNECTOR_SEARCH_CONFIG"],
    "",
  );

  const searchConfigMode = normalizeSearchConfigMode(
    readEnvString(["CONNECTOR_SEARCH_CONFIG_MODE"], "auto"),
  );

  const toolpanelDiscovery = normalizeToolpanelDiscovery(
    readEnvString(["TOOLPANEL_DISCOVERY"], "auto"),
  );

  return {
    apiKey,
    configDir,
    authUrl,
    toolpanelUrl,
    logLevel,
    searchConfigPath,
    searchConfigMode,
    toolpanelDiscovery,
  };
}

/**
 * Should the connector probe the local toolpanel liveness endpoint on this
 * boot? Returns `true` only when toolpanel detection is enabled and there is
 * a `toolpanelUrl` to probe against. Never throws.
 */
export function shouldAutoProbePanel(config: ToolconnectorConfig): boolean {
  if (config.toolpanelDiscovery !== "auto") return false;
  if (config.searchConfigMode === "file") return false;
  return config.toolpanelUrl.trim() !== "";
}

/**
 * Logger that writes to stderr (required for stdio MCP servers — stdout is
 * reserved for JSON-RPC).
 */
export class Logger {
  private threshold: number;

  constructor(level: LogLevel) {
    this.threshold = LOG_LEVELS[level];
  }

  debug(message: string, ...args: unknown[]): void {
    if (this.threshold <= LOG_LEVELS.debug) {
      console.error(`[toolconnector:debug] ${message}`, ...args);
    }
  }

  info(message: string, ...args: unknown[]): void {
    if (this.threshold <= LOG_LEVELS.info) {
      console.error(`[toolconnector:info] ${message}`, ...args);
    }
  }

  warn(message: string, ...args: unknown[]): void {
    if (this.threshold <= LOG_LEVELS.warn) {
      console.error(`[toolconnector:warn] ${message}`, ...args);
    }
  }

  error(message: string, ...args: unknown[]): void {
    if (this.threshold <= LOG_LEVELS.error) {
      console.error(`[toolconnector:error] ${message}`, ...args);
    }
  }
}
